--- #YAML:1.0
name:               PNI
version:            0.19
abstract:           Perl Node Interface
author:
    - G. Casati <fibo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               0
    Exporter:           0
    File::Find:         0
    File::Spec:         0
    File::Temp:         0.22
    JSON:               2.51
    Module::Pluggable:  0
    Scalar::Util:       0
    Test::More:         0
    Time::HiRes:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
