---
abstract: 'Perl Node Interface'
author:
  - 'G. Casati <fibo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PNI
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  JSON: 0
  Module::Pluggable: 0
  Mojolicious: 0
  Scalar::Util: 0
  Test::More: 0
  Time::HiRes: 0
version: v0.21.0
