--- #YAML:1.0
name:               PNI
version:            0.03
abstract:           Perl Node Interface
author:
    - G. Casati <fibo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:   0
    Test::More:   0.94
    Time::HiRes:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
