
=head1 NAME

PNI::Node::Perlvar

=head1 DESCRIPTION

It's a basic collection of PNI nodes implementing Perl predefined variables.

=head1 SEE ALSO

perlvar

=head1 AUTHOR

G. Casati , E<lt>fibo@cpan.orgE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2010 by G. Casati

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself .

=cut

